"""empty message

Revision ID: 068d42dae54a
Revises: 6cfa7d63e0e9
Create Date: 2026-07-20 21:09:21.995622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068d42dae54a'
down_revision = '6cfa7d63e0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_group', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
