"""empty message

Revision ID: 6cfa7d63e0e9
Revises: 
Create Date: 2026-07-19 02:27:19.047085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfa7d63e0e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.alter_column('paid_to',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.alter_column('paid_to',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
